apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcacoes-deployment
  labels:
    app: grpcacoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcacoes
  template:
    metadata:
      labels:
        app: grpcacoes
    spec:
      containers:
      - name: grpcacoes
        image: azurenapratica/grpacoes-mongodb-appinsights:latest
        env:
          - name: ApplicationInsights__InstrumentationKey
            value: CHAVE APPLICATION INSIGHTS
          - name: ConnectionStrings__DBAcoesMongoDB
            value: STRING CONEXÃO MONGODB
        ports:
        - containerPort: 80